services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - devops-network

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
    networks:
      - devops-network

  sonarqube:
    image: sonarqube
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db-sonarqube/sonar
    ports:
      - "9000:9000"
    networks:
      - devops-network

  db-sonarqube:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    networks:
      - devops-network

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-network
    restart: always

networks:
  devops-network:
    driver: bridge

volumes:
  jenkins_home:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
  sonarqube_db:
  nexus_data:
